/**
 * 任务模板数据 — 中风险、高风险、极高风险
 */

import type { MissionTemplate } from "./missions-templates-safe.js";

// ═══════════════════════════════════════════════════════════════════════════
// 中风险 / 高风险 / 极高风险模板
// ═══════════════════════════════════════════════════════════════════════════

export const DANGER_TEMPLATES: MissionTemplate[] = [
	// ── 中风险 (medium) ──
	{
		id: "escort-treasure", name: "押运珍宝", description: "替镖局押运一批珍贵瓷器至洛阳",
		category: "escort", risk: "medium", goldBase: [50, 120], xpBase: [25, 50],
		hpCost: [8, 20], planSteps: 2, successRate: 0.72, minLevel: 8,
		successDesc: "珍宝完好送达，镖局赏银丰厚", failDesc: "途中遭山贼伏击，货物损失过半",
		mbtiTags: ["S", "J", "E"],
	},
	{
		id: "rescue-hostage", name: "解救人质", description: "恶霸绑架了村长之女，前去解救",
		category: "rescue", risk: "medium", goldBase: [40, 100], xpBase: [30, 55],
		hpCost: [10, 25], planSteps: 2, successRate: 0.70, minLevel: 10,
		successDesc: "与恶霸激战，成功救出人质", failDesc: "恶霸人多势众，未能救出人质",
		mbtiTags: ["F", "E", "N"],
	},
	{
		id: "spy-mingjiao", name: "刺探明教", description: "潜入明教分坛打探消息",
		category: "investigation", risk: "medium", goldBase: [35, 80], xpBase: [25, 45],
		hpCost: [8, 18], planSteps: 2, successRate: 0.68, minLevel: 12,
		successDesc: "获得重要情报，雇主满意", failDesc: "被巡逻教众发现，仓皇逃出",
		mbtiTags: ["I", "N", "T"],
	},
	{
		id: "poison-investigation", name: "追查毒源", description: "星宿海毒物流入江湖，追查来源",
		category: "investigation", risk: "medium", goldBase: [45, 90], xpBase: [28, 50],
		hpCost: [10, 22], planSteps: 2, successRate: 0.65, minLevel: 15,
		successDesc: "追查到毒源并上报六扇门", failDesc: "中了埋伏，身中剧毒勉强逃脱",
		mbtiTags: ["N", "T", "I"],
	},
	{
		id: "eliminate-corrupt-spy", name: "刺杀朝廷奸细", description: "潜入客栈刺杀为鞑子卖命的奸细",
		category: "assassination", risk: "medium", goldBase: [52, 109], xpBase: [22, 51],
		hpCost: [9, 20], planSteps: 1, successRate: 0.69, minLevel: 6,
		successDesc: "奸细伏诛，大宋少了一个祸害", failDesc: "奸细武功不弱，反伤了你的手臂",
		mbtiTags: ["T","F"],
	},
	{
		id: "rescue-kidnapped-wife", name: "解救被掳民女", description: "从山贼窝中救出被掳走的良家女子",
		category: "rescue", risk: "medium", goldBase: [46, 108], xpBase: [21, 48],
		hpCost: [10, 21], planSteps: 2, successRate: 0.58, minLevel: 6,
		successDesc: "民女脱险，家人跪谢恩公", failDesc: "山贼人多势众，未能得手",
		mbtiTags: ["S","N"],
	},
	{
		id: "deliver-secret-missive", name: "传递密信", description: "将一封军中密信送到襄阳守将手中",
		category: "delivery", risk: "medium", goldBase: [37, 113], xpBase: [29, 55],
		hpCost: [8, 23], planSteps: 1, successRate: 0.6, minLevel: 7,
		successDesc: "密信安全送达，守将感激不已", failDesc: "路上被蒙古兵盘查，密信差点暴露",
		mbtiTags: ["E","I"],
	},
	{
		id: "learn-tai-chi", name: "习练太极拳", description: "跟随张真人学习太极拳的精要",
		category: "training", risk: "medium", goldBase: [40, 86], xpBase: [22, 51],
		hpCost: [9, 17], planSteps: 2, successRate: 0.71, minLevel: 6,
		successDesc: "领悟太极真意，功力更上一层", failDesc: "走火入魔，经络逆行了半日",
		mbtiTags: ["J","P"],
	},
	{
		id: "escort-refugees", name: "护送难民", description: "护送一批难民从边境撤往襄阳城",
		category: "escort", risk: "medium", goldBase: [54, 124], xpBase: [25, 56],
		hpCost: [13, 23], planSteps: 2, successRate: 0.63, minLevel: 12,
		successDesc: "难民安全入城，官府登记安置", failDesc: "途中遭遇流箭，数人受伤",
		mbtiTags: ["E","N","J"],
	},
	{
		id: "retrieve-stolen-manual", name: "夺回被盗秘籍", description: "从飞贼手中夺回被盗的武功秘籍",
		category: "retrieval", risk: "medium", goldBase: [48, 102], xpBase: [24, 52],
		hpCost: [11, 21], planSteps: 2, successRate: 0.64, minLevel: 11,
		successDesc: "秘籍完璧归赵，门派上下松了口气", failDesc: "飞贼轻功了得，追丢了",
		mbtiTags: ["I","S","P"],
	},
	{
		id: "investigate-ghost-sight", name: "调查鬼影疑案", description: "查明城中闹鬼传言的真相",
		category: "investigation", risk: "medium", goldBase: [44, 104], xpBase: [27, 58],
		hpCost: [13, 25], planSteps: 1, successRate: 0.63, minLevel: 7,
		successDesc: "鬼影是人为装神弄鬼，真相大白", failDesc: "被吓得不轻，什么也没查到",
		mbtiTags: ["S","T"],
	},
	{
		id: "escort-scholar", name: "护送赴考书生", description: "护送书生从四川赴京赶考",
		category: "escort", risk: "medium", goldBase: [42, 121], xpBase: [30, 62],
		hpCost: [11, 24], planSteps: 1, successRate: 0.74, minLevel: 12,
		successDesc: "书生平安抵达京城，准备应试", failDesc: "书生路上生了病，耽误了考期",
		mbtiTags: ["N","F","P"],
	},
	{
		id: "retrieve-sunken-cargo", name: "打捞沉船货物", description: "潜入江中打捞沉船上的贵重货物",
		category: "retrieval", risk: "medium", goldBase: [35, 114], xpBase: [23, 48],
		hpCost: [8, 17], planSteps: 1, successRate: 0.74, minLevel: 15,
		successDesc: "货物捞回大半，商行重谢", failDesc: "水下暗流湍急，差点被卷走",
		mbtiTags: ["T","J","P"],
	},
	{
		id: "assassinate-wolf-king", name: "猎杀狼王", description: "深入山林猎杀为害牲畜的独眼狼王",
		category: "assassination", risk: "medium", goldBase: [49, 127], xpBase: [23, 48],
		hpCost: [11, 25], planSteps: 1, successRate: 0.71, minLevel: 14,
		successDesc: "狼王被毙，牲畜再无后患", failDesc: "被狼群围住，仓皇逃回",
		mbtiTags: ["E","F","J"],
	},
	{
		id: "rescue-trapped-miner", name: "营救矿工", description: "深入坍塌的矿洞救出被困矿工",
		category: "rescue", risk: "medium", goldBase: [35, 88], xpBase: [29, 52],
		hpCost: [13, 30], planSteps: 2, successRate: 0.64, minLevel: 9,
		successDesc: "矿工被救出，阖家团圆", failDesc: "矿洞二次坍塌，救援受阻",
		mbtiTags: ["I","N","T"],
	},
	{
		id: "deliver-military-map", name: "运送军事地图", description: "将城防地图从临安送往襄阳",
		category: "delivery", risk: "medium", goldBase: [37, 107], xpBase: [28, 60],
		hpCost: [13, 24], planSteps: 1, successRate: 0.61, minLevel: 9,
		successDesc: "地图安全送达，守军如虎添翼", failDesc: "地图被金人探子截走了一半",
		mbtiTags: ["S","P"],
	},
	{
		id: "investigate-poison-well", name: "调查水井投毒", description: "查明村庄水井被人下毒的真相",
		category: "investigation", risk: "medium", goldBase: [49, 130], xpBase: [26, 57],
		hpCost: [9, 23], planSteps: 2, successRate: 0.58, minLevel: 10,
		successDesc: "投毒者被擒获，村庄转危为安", failDesc: "线索断掉了，投毒者仍在暗处",
		mbtiTags: ["E","S"],
	},
	{
		id: "train-iron-palm", name: "修炼铁砂掌", description: "在铁砂桶中苦练铁砂掌功夫",
		category: "training", risk: "medium", goldBase: [40, 125], xpBase: [26, 48],
		hpCost: [9, 26], planSteps: 2, successRate: 0.65, minLevel: 11,
		successDesc: "铁砂掌初有小成，碎砖如泥", failDesc: "手掌练伤，休养了半个月",
		mbtiTags: ["N","T"],
	},
	{
		id: "escort-medicine-team", name: "护送医疗队", description: "护送医疗队前往疫区救治百姓",
		category: "escort", risk: "medium", goldBase: [33, 81], xpBase: [22, 54],
		hpCost: [12, 23], planSteps: 1, successRate: 0.58, minLevel: 8,
		successDesc: "医疗队安全抵达，百姓得到救治", failDesc: "路上遇到山贼，药品被抢走部分",
		mbtiTags: ["I","F","J"],
	},
	{
		id: "retrieve-family-heirloom", name: "寻回家传宝刀", description: "从当铺赎回家道中落后典当的宝刀",
		category: "retrieval", risk: "medium", goldBase: [37, 110], xpBase: [30, 54],
		hpCost: [10, 25], planSteps: 1, successRate: 0.74, minLevel: 8,
		successDesc: "宝刀重回故主之手，锋芒依旧", failDesc: "当铺已经把宝刀卖给了别人",
		mbtiTags: ["T","S"],
	},
	{
		id: "assassinate-smuggler-chief", name: "刺杀走私头目", description: "潜入黑风寨刺杀走私违禁品的头目",
		category: "assassination", risk: "medium", goldBase: [53, 124], xpBase: [22, 39],
		hpCost: [11, 24], planSteps: 1, successRate: 0.6, minLevel: 17,
		successDesc: "头目伏诛，走私线被切断", failDesc: "头目身边护卫太多，未能近身",
		mbtiTags: ["E","P"],
	},
	{
		id: "rescue-captive-monk", name: "营救被困僧人", description: "从土匪手中救出化缘被困的少林僧人",
		category: "rescue", risk: "medium", goldBase: [55, 134], xpBase: [28, 54],
		hpCost: [9, 19], planSteps: 1, successRate: 0.75, minLevel: 7,
		successDesc: "僧人脱困，阿弥陀佛念了几遍", failDesc: "土匪要价太高，只好回去搬救兵",
		mbtiTags: ["J","N"],
	},
	{
		id: "deliver-antidote", name: "送解药", description: "将解药火速送往中毒的武林同道处",
		category: "delivery", risk: "medium", goldBase: [55, 140], xpBase: [26, 58],
		hpCost: [8, 23], planSteps: 1, successRate: 0.74, minLevel: 7,
		successDesc: "解药及时送到，中毒者脱离危险", failDesc: "路上耽搁了，解药送到时为时已晚",
		mbtiTags: ["S","E"],
	},
	{
		id: "investigate-missing-disciple", name: "调查失踪弟子", description: "查明门派弟子在山中失踪的真相",
		category: "investigation", risk: "medium", goldBase: [57, 105], xpBase: [30, 64],
		hpCost: [12, 27], planSteps: 2, successRate: 0.62, minLevel: 10,
		successDesc: "弟子被困陷阱，成功救回", failDesc: "山中迷路，连弟子带自己差点回不来",
		mbtiTags: ["I","T","P"],
	},
	{
		id: "train-dagger", name: "短刀术精进", description: "跟随高手学习短刀近身搏击之术",
		category: "training", risk: "medium", goldBase: [34, 85], xpBase: [25, 58],
		hpCost: [12, 21], planSteps: 1, successRate: 0.73, minLevel: 8,
		successDesc: "短刀术大有长进，师傅连连点头", failDesc: "练刀时不慎伤了自己的手指",
		mbtiTags: ["F","N"],
	},
	{
		id: "escort-witness", name: "护送证人", description: "将关键证人安全送到县衙大堂",
		category: "escort", risk: "medium", goldBase: [40, 119], xpBase: [23, 44],
		hpCost: [11, 20], planSteps: 1, successRate: 0.75, minLevel: 11,
		successDesc: "证人安全到堂，冤案得以昭雪", failDesc: "证人被人半路截走，下落不明",
		mbtiTags: ["E","J"],
	},
	{
		id: "retrieve-poison-antidote", name: "取回解药配方", description: "从毒医谷取回独家解毒配方",
		category: "retrieval", risk: "medium", goldBase: [36, 109], xpBase: [28, 55],
		hpCost: [12, 23], planSteps: 2, successRate: 0.65, minLevel: 17,
		successDesc: "配方到手，可解百毒", failDesc: "毒医谷机关重重，差点有去无回",
		mbtiTags: ["S","I"],
	},
	{
		id: "rescue-orphanage", name: "救助孤幼院", description: "从火场中救出孤幼院的孩子",
		category: "rescue", risk: "medium", goldBase: [46, 111], xpBase: [28, 53],
		hpCost: [13, 23], planSteps: 2, successRate: 0.58, minLevel: 16,
		successDesc: "孩子们安然无恙，众人齐声叫好", failDesc: "火势太大，只救出了一半",
		mbtiTags: ["T","E"],
	},
	{
		id: "investigate-cult-recruit", name: "调查邪教招募", description: "暗中调查邪教在民间秘密招募教众",
		category: "investigation", risk: "medium", goldBase: [36, 120], xpBase: [23, 41],
		hpCost: [10, 25], planSteps: 2, successRate: 0.63, minLevel: 16,
		successDesc: "邪教据点被端，教众被遣散", failDesc: "身份暴露，被邪教追杀了一路",
		mbtiTags: ["N","J","P"],
	},
	{
		id: "train-hidden-weapon", name: "暗器修炼", description: "在密林中苦练飞镖暗器手法",
		category: "training", risk: "medium", goldBase: [37, 107], xpBase: [28, 53],
		hpCost: [12, 25], planSteps: 1, successRate: 0.69, minLevel: 16,
		successDesc: "暗器百步穿杨，命中率大增", failDesc: "飞镖反弹误伤了自己",
		mbtiTags: ["F","S"],
	},
	// ── 高风险 (high) ──
	{
		id: "escort-imperial", name: "押送贡品", description: "替朝廷押送贡品至大都，途中必有江湖人觊觎",
		category: "escort", risk: "high", goldBase: [80, 200], xpBase: [40, 80],
		hpCost: [15, 35], planSteps: 3, successRate: 0.55, minLevel: 20,
		successDesc: "贡品安全送达，朝廷重赏", failDesc: "遭大批江湖人围攻，贡品被劫",
		mbtiTags: ["J", "S", "T"],
	},
	{
		id: "assassinate-traitor", name: "刺杀叛徒", description: "替门派清理门户，刺杀叛逃弟子",
		category: "assassination", risk: "high", goldBase: [70, 180], xpBase: [45, 85],
		hpCost: [18, 40], planSteps: 3, successRate: 0.50, minLevel: 25,
		successDesc: "叛徒伏诛，门派上下称颂", failDesc: "叛徒武功高强，你负伤败退",
		mbtiTags: ["I", "T", "N"],
	},
	{
		id: "rescue-prisoner", name: "劫狱救人", description: "闯入大理寺天牢救出蒙冤之人",
		category: "rescue", risk: "high", goldBase: [90, 220], xpBase: [50, 90],
		hpCost: [20, 45], planSteps: 3, successRate: 0.45, minLevel: 25,
		successDesc: "天牢救人成功，义薄云天", failDesc: "守卫森严，差点被抓",
		mbtiTags: ["F", "P", "E"],
	},
	{
		id: "retrieve-stolen-sword", name: "夺回名剑", description: "从盗剑高手手中夺回倚天剑",
		category: "retrieval", risk: "high", goldBase: [95, 192], xpBase: [46, 82],
		hpCost: [21, 43], planSteps: 3, successRate: 0.53, minLevel: 30,
		successDesc: "名剑归鞘，江湖传为佳话", failDesc: "盗剑人武功高强，败下阵来",
		mbtiTags: ["E","P"],
	},
	{
		id: "deliver-siege-weapon-plan", name: "运送攻城图纸", description: "将攻城器械图纸送到前线大营",
		category: "delivery", risk: "high", goldBase: [69, 157], xpBase: [48, 101],
		hpCost: [19, 39], planSteps: 2, successRate: 0.54, minLevel: 26,
		successDesc: "图纸安全送达，攻城在即", failDesc: "图纸被敌军截获，前锋部队陷入苦战",
		mbtiTags: ["I","N"],
	},
	{
		id: "investigate-treason", name: "调查通敌案", description: "深入调查朝中通敌卖国的幕后主使",
		category: "investigation", risk: "high", goldBase: [107, 205], xpBase: [46, 102],
		hpCost: [16, 37], planSteps: 2, successRate: 0.45, minLevel: 21,
		successDesc: "通敌证据确凿，奸臣伏法", failDesc: "证据被人销毁，反被诬陷",
		mbtiTags: ["S","T"],
	},
	{
		id: "train-jiuyang", name: "修炼九阳真经", description: "在密室中修炼九阳真经内功",
		category: "training", risk: "high", goldBase: [70, 203], xpBase: [37, 94],
		hpCost: [15, 37], planSteps: 3, successRate: 0.55, minLevel: 17,
		successDesc: "九阳神功初成，内力浑厚无比", failDesc: "走火入魔，经脉受损严重",
		mbtiTags: ["E","F","J"],
	},
	{
		id: "escort-general", name: "护送大将军", description: "护送岳元帅旧部安全突围",
		category: "escort", risk: "high", goldBase: [80, 167], xpBase: [48, 82],
		hpCost: [15, 34], planSteps: 2, successRate: 0.56, minLevel: 16,
		successDesc: "将军安全脱围，保留抗金火种", failDesc: "遭遇金兵主力，将军身负重伤",
		mbtiTags: ["N","T","P"],
	},
	{
		id: "assassinate-gold-envoy", name: "刺杀金国密使", description: "刺杀前来招降的金国密使",
		category: "assassination", risk: "high", goldBase: [63, 175], xpBase: [40, 94],
		hpCost: [19, 44], planSteps: 2, successRate: 0.43, minLevel: 29,
		successDesc: "密使伏诛，招降阴谋破产", failDesc: "密使护卫森严，刺杀失败反被追杀",
		mbtiTags: ["I","S"],
	},
	{
		id: "rescue-captive-general", name: "营救被俘将领", description: "深入敌营救出被俘的宋军将领",
		category: "rescue", risk: "high", goldBase: [102, 250], xpBase: [43, 92],
		hpCost: [19, 45], planSteps: 2, successRate: 0.48, minLevel: 25,
		successDesc: "将领被成功救出，全军振奋", failDesc: "敌营防守森严，未能突破",
		mbtiTags: ["J","F"],
	},
	{
		id: "retrieve-yanfei-letter", name: "取回岳飞遗书", description: "从秦桧府中取回岳元帅的绝笔信",
		category: "retrieval", risk: "high", goldBase: [89, 191], xpBase: [42, 93],
		hpCost: [15, 38], planSteps: 3, successRate: 0.52, minLevel: 23,
		successDesc: "遗书重见天日，忠魂得以昭雪", failDesc: "府中高手如云，差点折在里面",
		mbtiTags: ["T","S"],
	},
	{
		id: "deliver-reinforcement-order", name: "传送增援令", description: "突破封锁将增援令送到被困的襄阳城",
		category: "delivery", risk: "high", goldBase: [104, 243], xpBase: [43, 79],
		hpCost: [20, 47], planSteps: 2, successRate: 0.45, minLevel: 24,
		successDesc: "增援令送到，援军及时赶到", failDesc: "传令途中被截，城池危在旦夕",
		mbtiTags: ["E","N"],
	},
	{
		id: "investigate-demonic-cult", name: "调查魔教密谋", description: "潜入魔教查明日月神教的灭门计划",
		category: "investigation", risk: "high", goldBase: [96, 207], xpBase: [47, 101],
		hpCost: [24, 53], planSteps: 3, successRate: 0.48, minLevel: 27,
		successDesc: "魔教阴谋被揭露，各派有所防备", failDesc: "身份暴露，被魔教追杀千里",
		mbtiTags: ["I","P"],
	},
	{
		id: "train-drunken-fist", name: "修炼醉拳", description: "跟随苏乞儿学习失传的醉拳八式",
		category: "training", risk: "high", goldBase: [75, 213], xpBase: [38, 69],
		hpCost: [21, 43], planSteps: 3, successRate: 0.46, minLevel: 25,
		successDesc: "醉拳七式已通，拳风虎虎生威", failDesc: "真的喝醉了，拳没学会酒量涨了",
		mbtiTags: ["S","F"],
	},
	{
		id: "escort-secret-weapon", name: "押运神兵", description: "将新铸的玄铁重剑送往剑冢",
		category: "escort", risk: "high", goldBase: [101, 226], xpBase: [51, 104],
		hpCost: [20, 36], planSteps: 3, successRate: 0.48, minLevel: 24,
		successDesc: "玄铁重剑安全入库", failDesc: "路上遭遇觊觎神兵的各路高手围攻",
		mbtiTags: ["N","T"],
	},
	{
		id: "assassinate-pirate-king", name: "刺杀海盗头目", description: "潜入海岛刺杀劫掠沿海的海盗王",
		category: "assassination", risk: "high", goldBase: [95, 210], xpBase: [36, 73],
		hpCost: [23, 51], planSteps: 3, successRate: 0.43, minLevel: 15,
		successDesc: "海盗王被除，沿海百姓安居", failDesc: "海盗王武艺高强，险些丧命",
		mbtiTags: ["E","J","S"],
	},
	{
		id: "rescue-abducted-nun", name: "营救被掳师太", description: "从魔教手中救出峨眉派被掳的师太",
		category: "rescue", risk: "high", goldBase: [72, 212], xpBase: [36, 87],
		hpCost: [22, 44], planSteps: 3, successRate: 0.53, minLevel: 21,
		successDesc: "师太脱险，峨眉上下感恩戴德", failDesc: "魔教教主亲自出手，只得败退",
		mbtiTags: ["I","N","F"],
	},
	{
		id: "retrieve-dragon-slayer", name: "寻回屠龙刀", description: "从江湖纷争中夺回失踪的屠龙刀",
		category: "retrieval", risk: "high", goldBase: [90, 174], xpBase: [49, 108],
		hpCost: [20, 50], planSteps: 3, successRate: 0.46, minLevel: 30,
		successDesc: "屠龙刀归鞘，群雄觊觎之心暂息", failDesc: "夺刀之战中身负重伤，刀被人趁乱夺走",
		mbtiTags: ["S","P"],
	},
	{
		id: "deliver-spy-intel", name: "传送谍报", description: "将关键的蒙古军情送到宋军大营",
		category: "delivery", risk: "high", goldBase: [76, 233], xpBase: [36, 71],
		hpCost: [20, 47], planSteps: 3, successRate: 0.52, minLevel: 19,
		successDesc: "情报及时送达，宋军避开了埋伏", failDesc: "被蒙古探子发现，情报泄露",
		mbtiTags: ["T","J"],
	},
	{
		id: "train-dugu-nine", name: "研习独孤九剑", description: "在剑冢中研习风清扬留下的独孤九剑",
		category: "training", risk: "high", goldBase: [107, 236], xpBase: [35, 68],
		hpCost: [15, 30], planSteps: 3, successRate: 0.44, minLevel: 27,
		successDesc: "九剑之意领悟大半，剑术突飞猛进", failDesc: "九剑太过深奥，一头雾水",
		mbtiTags: ["E","F"],
	},
	// ── 极高风险 (extreme) ──
	{
		id: "escort-dragon-slayer", name: "护送屠龙刀", description: "护送屠龙刀至武当山，天下武林尽出",
		category: "escort", risk: "extreme", goldBase: [200, 500], xpBase: [80, 150],
		hpCost: [25, 55], planSteps: 4, successRate: 0.30, minLevel: 35,
		successDesc: "屠龙刀安抵武当，张真人亲自致谢", failDesc: "群雄围攻，刀落人伤",
		mbtiTags: ["E", "J", "S"],
	},
	{
		id: "steal-imperial-seal", name: "盗取传国玉玺", description: "潜入皇宫盗取传国玉玺",
		category: "retrieval", risk: "extreme", goldBase: [250, 600], xpBase: [90, 160],
		hpCost: [30, 60], planSteps: 4, successRate: 0.25, minLevel: 40,
		successDesc: "神不知鬼不觉取走玉玺", failDesc: "被大内高手发现，九死一生逃出",
		mbtiTags: ["I", "N", "P"],
	},
	{
		id: "destroy-evil-cult", name: "剿灭邪教分坛", description: "率众攻打血刀门分坛",
		category: "assassination", risk: "extreme", goldBase: [180, 450], xpBase: [70, 130],
		hpCost: [28, 50], planSteps: 4, successRate: 0.35, minLevel: 35,
		successDesc: "分坛被毁，武林太平", failDesc: "邪教教主出手，伤亡惨重",
		mbtiTags: ["E", "T", "J"],
	},
	{
		id: "escort-imperial-fleet", name: "护送皇家车队", description: "护送满载军饷的皇家车队穿越百里敌境",
		category: "escort", risk: "extreme", goldBase: [268, 503], xpBase: [62, 131],
		hpCost: [36, 68], planSteps: 3, successRate: 0.28, minLevel: 47,
		successDesc: "车队安全抵达，军饷一分不少", failDesc: "途中遭遇大规模伏击，军饷尽失",
		mbtiTags: ["N","S"],
	},
	{
		id: "rescue-sect-leader", name: "营救掌门", description: "从天牢中救出被奸臣陷害入狱的掌门",
		category: "rescue", risk: "extreme", goldBase: [233, 634], xpBase: [93, 154],
		hpCost: [31, 57], planSteps: 3, successRate: 0.2, minLevel: 31,
		successDesc: "掌门脱困，门派免于覆灭", failDesc: "天牢守卫森严，营救未果反被擒",
		mbtiTags: ["I","T","P"],
	},
	{
		id: "deliver-dragon-vein-map", name: "运送龙脉图", description: "将关乎国运的龙脉图送到武当山",
		category: "delivery", risk: "extreme", goldBase: [156, 528], xpBase: [61, 160],
		hpCost: [25, 60], planSteps: 4, successRate: 0.27, minLevel: 32,
		successDesc: "龙脉图安全入藏武当金殿", failDesc: "各路人马蜂拥而至，龙脉图下落不明",
		mbtiTags: ["J","E"],
	},
	{
		id: "investigate-court-conspiracy", name: "揭露宫廷阴谋", description: "调查宫中太监勾结外敌颠覆朝政的惊天阴谋",
		category: "investigation", risk: "extreme", goldBase: [247, 546], xpBase: [65, 171],
		hpCost: [31, 60], planSteps: 3, successRate: 0.3, minLevel: 31,
		successDesc: "阴谋败露，奸阉伏法，社稷安宁", failDesc: "调查深入时身份暴露，九死一生",
		mbtiTags: ["S","F"],
	},
	{
		id: "train-yijinjing", name: "修炼易筋经", description: "在少林藏经阁中修炼达摩祖师传下的易筋经",
		category: "training", risk: "extreme", goldBase: [174, 417], xpBase: [82, 152],
		hpCost: [30, 61], planSteps: 3, successRate: 0.26, minLevel: 35,
		successDesc: "易筋经大成，脱胎换骨", failDesc: "经脉逆行，武功尽废",
		mbtiTags: ["N","P"],
	},
	{
		id: "assassinate-demon-lord", name: "刺杀魔教教主", description: "只身潜入黑木崖刺杀东方不败",
		category: "assassination", risk: "extreme", goldBase: [165, 491], xpBase: [65, 166],
		hpCost: [30, 63], planSteps: 3, successRate: 0.35, minLevel: 41,
		successDesc: "东方不败授首，魔教群龙无首", failDesc: "东方不败的葵花宝典出神入化，惨败而归",
		mbtiTags: ["T","I"],
	},
	{
		id: "retrieve-nine-yin-manual", name: "夺取九阴真经", description: "从华山论剑的混战中夺取九阴真经",
		category: "retrieval", risk: "extreme", goldBase: [188, 504], xpBase: [90, 165],
		hpCost: [26, 64], planSteps: 4, successRate: 0.32, minLevel: 40,
		successDesc: "九阴真经到手，天下武功尽在掌握", failDesc: "各路高手围攻，真经落入他人之手",
		mbtiTags: ["E","S","J"],
	},
];
